//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homuai.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homuai.Domain.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schedule available. Ask {0} to come here and create ;).
        /// </summary>
        public static string DESCRIPTION_CREATE_CLEANING_SCHEDULE {
            get {
                return ResourceManager.GetString("DESCRIPTION_CREATE_CLEANING_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today it is exactly {0} that you share a home :).
        /// </summary>
        public static string DESCRIPTION_DATE_JOINED_THE_HOUSE {
            get {
                return ResourceManager.GetString("DESCRIPTION_DATE_JOINED_THE_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask {0} to go to the option &quot;Home, sweet home&quot; and in the &quot;Rooms&quot; tab register the rooms for the schedule..
        /// </summary>
        public static string MESSAGE_REGISTER_ROOM {
            get {
                return ResourceManager.GetString("MESSAGE_REGISTER_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to go to the option &quot;Home, sweet home&quot; and in the &quot;Rooms&quot; tab register the rooms for the schedule..
        /// </summary>
        public static string MESSAGE_REGISTER_ROOM_ADMIN {
            get {
                return ResourceManager.GetString("MESSAGE_REGISTER_ROOM_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string TITLE_AND {
            get {
                return ResourceManager.GetString("TITLE_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string TITLE_DAY {
            get {
                return ResourceManager.GetString("TITLE_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string TITLE_DAYS {
            get {
                return ResourceManager.GetString("TITLE_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string TITLE_MONTH {
            get {
                return ResourceManager.GetString("TITLE_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string TITLE_MONTHS {
            get {
                return ResourceManager.GetString("TITLE_MONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string TITLE_YEAR {
            get {
                return ResourceManager.GetString("TITLE_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string TITLE_YEARS {
            get {
                return ResourceManager.GetString("TITLE_YEARS", resourceCulture);
            }
        }
    }
}
