//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homuai.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homuai.Domain.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schedule available. Ask {0} to come here and create ;).
        /// </summary>
        public static string DESCRIPTION_CREATE_CLEANING_SCHEDULE {
            get {
                return ResourceManager.GetString("DESCRIPTION_CREATE_CLEANING_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today it is exactly {0} that you share a home :).
        /// </summary>
        public static string DESCRIPTION_DATE_JOINED_THE_HOUSE {
            get {
                return ResourceManager.GetString("DESCRIPTION_DATE_JOINED_THE_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask {0} to go to the option &quot;Home, sweet home&quot; and in the &quot;Rooms&quot; tab register the rooms for the schedule..
        /// </summary>
        public static string MESSAGE_REGISTER_ROOM {
            get {
                return ResourceManager.GetString("MESSAGE_REGISTER_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to go to the option &quot;Home, sweet home&quot; and in the &quot;Rooms&quot; tab register the rooms for the schedule..
        /// </summary>
        public static string MESSAGE_REGISTER_ROOM_ADMIN {
            get {
                return ResourceManager.GetString("MESSAGE_REGISTER_ROOM_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} product will expire in three days..
        /// </summary>
        public static string NOTIFICATION_MESSAGE_3_DAYS_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_3_DAYS_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} product will expire next week..
        /// </summary>
        public static string NOTIFICATION_MESSAGE_7_DAYS_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_7_DAYS_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter in the app and check ;).
        /// </summary>
        public static string NOTIFICATION_MESSAGE_CLEANING_SCHEDULE_CREATED {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_CLEANING_SCHEDULE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone asked you to clean the room(s) for which you are responsible 👍.
        /// </summary>
        public static string NOTIFICATION_MESSAGE_CLEANING_SCHEDULE_REMINDER {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_CLEANING_SCHEDULE_REMINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter in the app and check :).
        /// </summary>
        public static string NOTIFICATION_MESSAGE_CLEANING_SCHEDULE_UPDATED {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_CLEANING_SCHEDULE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cleaning task ({0}) has been rated :) Enter the app and check ✔️.
        /// </summary>
        public static string NOTIFICATION_MESSAGE_CLEANING_TASK_RATED {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_CLEANING_TASK_RATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} product has been deleted: it has been expired for more than two days..
        /// </summary>
        public static string NOTIFICATION_MESSAGE_DELETED_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_DELETED_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received an order and it is waiting for you ✈️.
        /// </summary>
        public static string NOTIFICATION_MESSAGE_DELIVERY_RECEIVED {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_DELIVERY_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good luck with your new journey 🚀.
        /// </summary>
        public static string NOTIFICATION_MESSAGE_REMOVED_FROM_HOME {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_REMOVED_FROM_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cleaned the {1}, uhuu. You can now go to the App and rate the task ✔️.
        /// </summary>
        public static string NOTIFICATION_MESSAGE_ROOM_CLEANED {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_ROOM_CLEANED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} product has the expiration date for today..
        /// </summary>
        public static string NOTIFICATION_MESSAGE_TODAY_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_TODAY_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} product has the expiration date for tomorrow..
        /// </summary>
        public static string NOTIFICATION_MESSAGE_TOMORROW_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_TOMORROW_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, it&apos;s been {0} days since you cleaned {1}. You can do it, help keep everything organized  🥰.
        /// </summary>
        public static string NOTIFICATION_MESSAGE_TOTAL_DAYS_WITHOUT_CLEANING_ROOM {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_TOTAL_DAYS_WITHOUT_CLEANING_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} product expiration two days ago..
        /// </summary>
        public static string NOTIFICATION_MESSAGE_TWO_DAYS_PASSED_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_TWO_DAYS_PASSED_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} product has the expiration date for yesterday..
        /// </summary>
        public static string NOTIFICATION_MESSAGE_YESTERDAY_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_YESTERDAY_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 days until product expiration ⌛.
        /// </summary>
        public static string NOTIFICATION_TITLE_3_DAYS_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_3_DAYS_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days until product expiration ⌛.
        /// </summary>
        public static string NOTIFICATION_TITLE_7_DAYS_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_7_DAYS_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean room 💦.
        /// </summary>
        public static string NOTIFICATION_TITLE_CLEAN_ROOM_CLEANED {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_CLEAN_ROOM_CLEANED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning Schedule created 🏡.
        /// </summary>
        public static string NOTIFICATION_TITLE_CLEANING_SCHEDULE_CREATED {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_CLEANING_SCHEDULE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning Schedule reminder 😶.
        /// </summary>
        public static string NOTIFICATION_TITLE_CLEANING_SCHEDULE_REMINDER {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_CLEANING_SCHEDULE_REMINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning Schedule updated 🏡.
        /// </summary>
        public static string NOTIFICATION_TITLE_CLEANING_SCHEDULE_UPDATED {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_CLEANING_SCHEDULE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning task rated 🌟.
        /// </summary>
        public static string NOTIFICATION_TITLE_CLEANING_TASK_RATED {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_CLEANING_TASK_RATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted product ♻.
        /// </summary>
        public static string NOTIFICATION_TITLE_DELETED_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_DELETED_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery received 📬.
        /// </summary>
        public static string NOTIFICATION_TITLE_DELIVERY_RECEIVED {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_DELIVERY_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been removed from Home.
        /// </summary>
        public static string NOTIFICATION_TITLE_REMOVED_FROM_HOME {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_REMOVED_FROM_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have product with expiration date for TODAY ⚠.
        /// </summary>
        public static string NOTIFICATION_TITLE_TODAY_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_TODAY_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✘ TOMORROW, you have product with expiration date for TOMORROW.
        /// </summary>
        public static string NOTIFICATION_TITLE_TOMORROW_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_TOMORROW_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two days passed and ⌚.
        /// </summary>
        public static string NOTIFICATION_TITLE_TWO_DAYS_PASSED_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_TWO_DAYS_PASSED_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEY, you have a product that expired yesterday ⌚.
        /// </summary>
        public static string NOTIFICATION_TITLE_YESTERDAY_PRODUCT_EXPIRATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_TITLE_YESTERDAY_PRODUCT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string TITLE_AND {
            get {
                return ResourceManager.GetString("TITLE_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string TITLE_DAY {
            get {
                return ResourceManager.GetString("TITLE_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string TITLE_DAYS {
            get {
                return ResourceManager.GetString("TITLE_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string TITLE_MONTH {
            get {
                return ResourceManager.GetString("TITLE_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string TITLE_MONTHS {
            get {
                return ResourceManager.GetString("TITLE_MONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string TITLE_YEAR {
            get {
                return ResourceManager.GetString("TITLE_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string TITLE_YEARS {
            get {
                return ResourceManager.GetString("TITLE_YEARS", resourceCulture);
            }
        }
    }
}
