//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homuai.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceTextException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTextException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homuai.Exception.ResourceTextException", typeof(ResourceTextException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address must be entered..
        /// </summary>
        public static string ADDRESS_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to set the cleaning schedule when NO users have tasks..
        /// </summary>
        public static string ALL_USER_WITHOUT_CLEANING_TASKS {
            get {
                return ResourceManager.GetString("ALL_USER_WITHOUT_CLEANING_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City&apos;s name must be entered..
        /// </summary>
        public static string CITY_EMPTY {
            get {
                return ResourceManager.GetString("CITY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cleaning schedule has already been created..
        /// </summary>
        public static string CLEANING_SCHEDULE_ALREADY_CREATED {
            get {
                return ResourceManager.GetString("CLEANING_SCHEDULE_ALREADY_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must be entered..
        /// </summary>
        public static string CODE_EMPTY {
            get {
                return ResourceManager.GetString("CODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is invalid..
        /// </summary>
        public static string CODE_INVALID {
            get {
                return ResourceManager.GetString("CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password or verification code..
        /// </summary>
        public static string CODE_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("CODE_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a code to reset your password..
        /// </summary>
        public static string CODE_RESET_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CODE_RESET_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the administrator has been lost..
        /// </summary>
        public static string CONNECTION_ADMINISTRATOR_LOST {
            get {
                return ResourceManager.GetString("CONNECTION_ADMINISTRATOR_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Country&apos;s name must be entered..
        /// </summary>
        public static string COUNTRY_EMPTY {
            get {
                return ResourceManager.GetString("COUNTRY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password must be entered..
        /// </summary>
        public static string CURRENT_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is invalid..
        /// </summary>
        public static string CURRENT_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be before {0}..
        /// </summary>
        public static string DATE_MUST_BE_LESS_THAN {
            get {
                return ResourceManager.GetString("DATE_MUST_BE_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duedate must be after today..
        /// </summary>
        public static string DUEDATE_MUST_BE_GRATER_THAN_TODAY {
            get {
                return ResourceManager.GetString("DUEDATE_MUST_BE_GRATER_THAN_TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address has already been registered..
        /// </summary>
        public static string EMAIL_ALREADYBEENREGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADYBEENREGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail must be entered..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail is invalid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contacts cannot have the same phone number..
        /// </summary>
        public static string EMERGENCY_CONTACT_SAME_PHONENUMBER {
            get {
                return ResourceManager.GetString("EMERGENCY_CONTACT_SAME_PHONENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An emergency contact must be informed..
        /// </summary>
        public static string EMERGENCYCONTACT_EMPTY {
            get {
                return ResourceManager.GetString("EMERGENCYCONTACT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can inform a maximum of 2 emergency contacts..
        /// </summary>
        public static string EMERGENCYCONTACT_MAX_TWO {
            get {
                return ResourceManager.GetString("EMERGENCYCONTACT_MAX_TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired code. Request a new one..
        /// </summary>
        public static string EXPIRED_CODE {
            get {
                return ResourceManager.GetString("EXPIRED_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend was not found..
        /// </summary>
        public static string FRIEND_NOT_FOUND {
            get {
                return ResourceManager.GetString("FRIEND_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters..
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid task..
        /// </summary>
        public static string INVALID_TASK {
            get {
                return ResourceManager.GetString("INVALID_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user..
        /// </summary>
        public static string INVALID_USER {
            get {
                return ResourceManager.GetString("INVALID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menssage must be entered..
        /// </summary>
        public static string MESSAGE_EMPTY {
            get {
                return ResourceManager.GetString("MESSAGE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid monthly rent..
        /// </summary>
        public static string MONTHLYRENT_INVALID {
            get {
                return ResourceManager.GetString("MONTHLYRENT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be entered..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The neighborhood must be entered..
        /// </summary>
        public static string NEIGHBORHOOD_EMPTY {
            get {
                return ResourceManager.GetString("NEIGHBORHOOD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be entered..
        /// </summary>
        public static string NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password must be entered..
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A phonenumber must be entered for the Emergency contact..
        /// </summary>
        public static string PHONENUMBER_EMERGENCY_CONTACT_EMPTY {
            get {
                return ResourceManager.GetString("PHONENUMBER_EMERGENCY_CONTACT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A phone number must be entered..
        /// </summary>
        public static string PHONENUMBER_EMPTY {
            get {
                return ResourceManager.GetString("PHONENUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter a maximum of 2 phonenumbers..
        /// </summary>
        public static string PHONENUMBER_MAX_TWO {
            get {
                return ResourceManager.GetString("PHONENUMBER_MAX_TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone numbers are the same..
        /// </summary>
        public static string PHONENUMBERS_ARE_SAME {
            get {
                return ResourceManager.GetString("PHONENUMBERS_ARE_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product name must be entered..
        /// </summary>
        public static string PRODUCT_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product was not found..
        /// </summary>
        public static string PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The push notification id is invalid..
        /// </summary>
        public static string PUSHNOTIFICATION_INVALID {
            get {
                return ResourceManager.GetString("PUSHNOTIFICATION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of products is invalid..
        /// </summary>
        public static string QUANTITY_PRODUCTS_INVALID {
            get {
                return ResourceManager.GetString("QUANTITY_PRODUCTS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must rate the task with a score between 0 and 5..
        /// </summary>
        public static string RATE_SCORE_BETWEEN_ZERO_FIVE {
            get {
                return ResourceManager.GetString("RATE_SCORE_BETWEEN_ZERO_FIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only rate tasks on the current month&apos;s schedule..
        /// </summary>
        public static string RATE_TASK_JUST_CURRENT_MONTHS_SCHEDULE {
            get {
                return ResourceManager.GetString("RATE_TASK_JUST_CURRENT_MONTHS_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only record cleaning records for the current month and up to 3 days before today..
        /// </summary>
        public static string RECORD_CLEANING_ROOM_INVALID_DATE {
            get {
                return ResourceManager.GetString("RECORD_CLEANING_ROOM_INVALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship must be entered..
        /// </summary>
        public static string RELATIONSHIPTO_EMPTY {
            get {
                return ResourceManager.GetString("RELATIONSHIPTO_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There area rooms that do not exist in Home..
        /// </summary>
        public static string ROOM_DOES_NOT_EXIST_HOME {
            get {
                return ResourceManager.GetString("ROOM_DOES_NOT_EXIST_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room&apos;s name must be entered..
        /// </summary>
        public static string ROOM_EMPTY {
            get {
                return ResourceManager.GetString("ROOM_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a room with this name..
        /// </summary>
        public static string ROOM_NAME_EXIST {
            get {
                return ResourceManager.GetString("ROOM_NAME_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The State must be entered..
        /// </summary>
        public static string STATEPROVINCE_EMPTY {
            get {
                return ResourceManager.GetString("STATEPROVINCE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Emergency contact&apos;s name must be entered..
        /// </summary>
        public static string THE_NAME_EMERGENCY_CONTACT_INVALID {
            get {
                return ResourceManager.GetString("THE_NAME_EMERGENCY_CONTACT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Relationship with the Emergency contact must be entered..
        /// </summary>
        public static string THE_RELATIONSHIP_EMERGENCY_CONTACT_INVALID {
            get {
                return ResourceManager.GetString("THE_RELATIONSHIP_EMERGENCY_CONTACT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are duplicate users in the request..
        /// </summary>
        public static string THERE_ARE_DUPLICATE_USERS_REQUEST {
            get {
                return ResourceManager.GetString("THERE_ARE_DUPLICATE_USERS_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are duplicated rooms..
        /// </summary>
        public static string THERE_ARE_DUPLICATED_ROOMS {
            get {
                return ResourceManager.GetString("THERE_ARE_DUPLICATED_ROOMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are users with duplicate tasks in the request..
        /// </summary>
        public static string THERE_ARE_USERS_DUPLICATE_TASKS_REQUEST {
            get {
                return ResourceManager.GetString("THERE_ARE_USERS_DUPLICATE_TASKS_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a clean room record for this date..
        /// </summary>
        public static string THERE_IS_CLEAN_ROOM_RECORD_THIS_DATE {
            get {
                return ResourceManager.GetString("THERE_IS_CLEAN_ROOM_RECORD_THIS_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product&apos;s type is invalid..
        /// </summary>
        public static string TYPE_PRODUCTS_INVALID {
            get {
                return ResourceManager.GetString("TYPE_PRODUCTS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow error.
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already part of a home. This operation is not allowed at this time..
        /// </summary>
        public static string USER_IS_PART_OF_A_HOME {
            get {
                return ResourceManager.GetString("USER_IS_PART_OF_A_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User and/or password is invalid..
        /// </summary>
        public static string USER_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("USER_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this resource..
        /// </summary>
        public static string USER_WITHOUT_PERMISSION_ACCESS_RESOURCE {
            get {
                return ResourceManager.GetString("USER_WITHOUT_PERMISSION_ACCESS_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already rated this task..
        /// </summary>
        public static string YOU_ALREADY_RATE_THIS_TASK {
            get {
                return ResourceManager.GetString("YOU_ALREADY_RATE_THIS_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot perform this action..
        /// </summary>
        public static string YOU_CANNNOT_PERMORM_THIS_ACTION {
            get {
                return ResourceManager.GetString("YOU_CANNNOT_PERMORM_THIS_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not rate your own task..
        /// </summary>
        public static string YOU_CANNOT_RATE_YOUR_OWN_TASK {
            get {
                return ResourceManager.GetString("YOU_CANNOT_RATE_YOUR_OWN_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Zip Code must be entered..
        /// </summary>
        public static string ZIPCODE_EMPTY {
            get {
                return ResourceManager.GetString("ZIPCODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CEP is invalid. Must be with the format XX.XXX-XXX.
        /// </summary>
        public static string ZIPCODE_INVALID_BRAZIL {
            get {
                return ResourceManager.GetString("ZIPCODE_INVALID_BRAZIL", resourceCulture);
            }
        }
    }
}
