//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homuai.EmailHelper.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a friend.
        /// </summary>
        public static string SUBJECT_REMOVE_FRIEND {
            get {
                return ResourceManager.GetString("SUBJECT_REMOVE_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string SUBJECT_RESET_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("SUBJECT_RESET_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But remember, don&apos;t leave it for later, as this code will only be valid for 1 hour, agreed?.
        /// </summary>
        public static string TITLE_BUT_REMEMBER_DONT_LEAVE_FOR_LATER_ONE_HOUR {
            get {
                return ResourceManager.GetString("TITLE_BUT_REMEMBER_DONT_LEAVE_FOR_LATER_ONE_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But remember, don&apos;t leave it for later as this code will only be valid for 10 minutes, agreed?.
        /// </summary>
        public static string TITLE_BUT_REMEMBER_DONT_LEAVE_FOR_LATER_TEN_MINUTES {
            get {
                return ResourceManager.GetString("TITLE_BUT_REMEMBER_DONT_LEAVE_FOR_LATER_TEN_MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code to remove a friend.
        /// </summary>
        public static string TITLE_CODE_REMOVE_FRIEND {
            get {
                return ResourceManager.GetString("TITLE_CODE_REMOVE_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code to change your password.
        /// </summary>
        public static string TITLE_CODE_RESET_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_CODE_RESET_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}.
        /// </summary>
        public static string TITLE_HI_NAME {
            get {
                return ResourceManager.GetString("TITLE_HI_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent you this email in response to your request to reset your password on Homuai App..
        /// </summary>
        public static string TITLE_NEED_TO_RESET_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_NEED_TO_RESET_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ignore this email if you did not request a password change..
        /// </summary>
        public static string TITLE_PLEASE_IGNORE_THIS_EMAIL_NOT_REQUEST_PASSWORD_CHANGE {
            get {
                return ResourceManager.GetString("TITLE_PLEASE_IGNORE_THIS_EMAIL_NOT_REQUEST_PASSWORD_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the code below to remove your friend from Home membership:.
        /// </summary>
        public static string TITLE_TO_REMOVE_FRIEND_USE_CODE_BELOW {
            get {
                return ResourceManager.GetString("TITLE_TO_REMOVE_FRIEND_USE_CODE_BELOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reset your password, please follow use the code below:.
        /// </summary>
        public static string TITLE_TO_RESET_PASSWORD_USE_CODE_BELOW {
            get {
                return ResourceManager.GetString("TITLE_TO_RESET_PASSWORD_USE_CODE_BELOW", resourceCulture);
            }
        }
    }
}
